networks:
  dockernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
services:
  ubuntu_os:
    hostname: dev_env
    networks:
      dockernet:
        ipv4_address: 192.168.55.10
        aliases:
        - dev_env
    build:
      args:
        expose_port: '8888'
        arg_uid: "${MY_UID}"
        arg_gid: "${MY_GID}"
      context: ./
      dockerfile: Dockerfile
    container_name: ubuntu_os
    deploy:
      resources:
        limits:
          cpus: 0.7
          memory: 4G
        reservations:
          cpus: 0.25
          memory: 1G
    ports:
      - 8888:8088
      - 3000:3000
      - "8822:22"
    restart: always
    user: "${MY_UID}"
    volumes:
      - ./data/:/host_mount/:rw
      - ./entrypoint/:/entrypoint/
version: '3.8'
